#!/bin/sh

which docker > /dev/null 2>&1
if [ $? -ne 0 ]; then
	echo "docker not in path"
	exit 1
fi

if [ $# -ge 1 ]; then
	DBADDR=$1
fi

DOCKER_NAME="dbt5-driver-0"

# Ensure the executable has the correct permissions
docker exec -u root -it $DOCKER_NAME chmod +x /usr/local/src/dbt5/builds/release/src/BrokerageHouse

docker exec -u postgres:postgres -it $DOCKER_NAME \
        /usr/local/src/dbt5/builds/release/src/BrokerageHouse -h $DBADDR -d dbt5 -o /tmp
